version: '3.8'

services:
  backend:
    build: ./backend
    container_name: gedo-cimcop-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=gedo-cimcop-secret-key-production-2024
      - DATABASE_URL=sqlite:///src/database/app.db
    volumes:
      - backend_data:/app/src/database
      - uploads_data:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    container_name: gedo-cimcop-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend_data:
    driver: local
  uploads_data:
    driver: local

networks:
  default:
    name: gedo-cimcop-network

