services:
  - type: web
    name: gedo-cimcop-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    pythonVersion: 3.10.13  # ✅ Adicionado para evitar erro com pandas
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: gedo-cimcop-super-secret-key-production-2024
      - key: FRONTEND_URL
        value: https://seu-frontend.vercel.app
      - key: PORT
        value: 5000
