services:
  - type: web
    name: gedo-cimcop-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    runtime: python
    pythonVersion: "3.10.13"
    rootDir: ./backend
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: gedo-cimcop-super-secret-key-production-2024
      - key: JWT_SECRET_KEY
        value: gedo-cimcop-jwt-secret-key-2024
      - key: FRONTEND_URL
        value: https://seu-frontend.vercel.app
      - key: PORT
        value: 5000

  # Banco de dados PostgreSQL
  - type: pserv
    name: gedo-cimcop-db
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.postgres
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

databases:
  - name: gedo-cimcop-db
    databaseName: gedo_cimcop
    user: gedo_user
